TEST_ARTIFICIAL_NETWORKS = {
    ("artificial_er", "network_15"),
    ("artificial_er", "network_20"),
    ("artificial_er", "network_40"),
    ("artificial_er", "network_45"),
    ("artificial_er", "network_71"),
    ("artificial_er", "network_78"),
    ("artificial_er", "network_79"),
    ("artificial_er", "network_80"),
    ("artificial_pa", "network_7"),
    ("artificial_pa", "network_23"),
    ("artificial_pa", "network_39"),
    ("artificial_pa", "network_57"),
    ("artificial_pa", "network_58"),
    ("artificial_pa", "network_75"),
    ("artificial_pa", "network_85"),
    ("artificial_pa", "network_95"),
    ("artificial_pa", "network_22"),
    ("artificial_pa", "network_68"),
    ("artificial_pa", "network_83"),
    ("artificial_pa", "network_93"),
}
